### ISSUE TITLE
Mod Crashing Game Without Optifine

### ISSUE THREAD

**Issue by Ospoortus** [b3spectacled/modernbetaforge#12] opened 2024-12-29 17:00 UTC
When I remove Optifine the mod starts crashing the game for some reason. It works with Optifine and it works without this mod nor Optifine.
I am using the 1.12.2 version.
Crash Log:
https://mclo.gs/GpMqceh

**Comment by b3spectacled** [comment] 2024-12-29 21:10
Hi, thanks for reporting.

This is a weird issue. I tested using a clean instance with my mod, Optifine 1.12.2 HD U G5, and Mixin Compatiblity (which apparently is sufficient for fulfilling the mixin dependency), but couldn't reproduce the issue.

It crashes specifically when my mod attempts to inject code into where Minecraft calculates fog color. If I had to guess, one of your other mods edits the base class somehow such that my mod can't locate the appropriate place to do that. Optifine, if it's still an invasive mod these days, might be replacing that edit with something that resembles vanilla code, thus allowing it to work.

I'll look into this.

**Comment by b3spectacled** [comment] 2024-12-30 05:25
I've identified the issue as being due to Galacticraft. Seeing as it is a very popular mod that does funky bytecode injection which interferes with my mod, I'll simply have to figure out how to disable those particular clientside features from my mod's end.

**Comment by b3spectacled** [comment] 2024-12-30 07:07
I have a workaround that simply disables certain cosmetic/visual features when Galacticraft is loaded. Not much more I can do there unfortunately.

I will close out the issue when the next update is posted.

**Comment by b3spectacled** [comment] 2024-12-31 07:28
Should be fixed with 1.12.2-1.4.0.0, thanks!

**Closed as completed by b3spectacled** 2024-12-31 07:28 UTC
Labels: bug
