### ISSUE TITLE
Issue with galacticraft

### ISSUE THREAD

**Issue by darklysteamgear** [b3spectacled/modernbetaforge#2] opened 2023-05-09 20:58 UTC
Hello,
I'm not sure why, but this mod spams the logs when galacticraft is installed. below is a snippet of what the log is saying

[16:52:09] [Server thread/ERROR]: Error in another mod's worldgen.  This is *NOT* a Galacticraft bug, report it to the other mod please.
[16:52:09] [Server thread/ERROR]: Details:- Dimension:58  Chunk cx,cz:-19,31  Seed:-6984854390176336655
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: java.lang.NullPointerException
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.api.world.gen.ChunkSource.getNearestStructurePos(ChunkSource.java:406)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.world.gen.ModernBetaChunkGenerator.func_180513_a(ModernBetaChunkGenerator.java:70)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:207)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at java.lang.Thread.run(Thread.java:745)
[16:52:09] [Server thread/ERROR]: Error in another mod's worldgen.  This is *NOT* a Galacticraft bug, report it to the other mod please.
[16:52:09] [Server thread/ERROR]: Details:- Dimension:58  Chunk cx,cz:-19,32  Seed:-6984854390176336655
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: java.lang.NullPointerException
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.api.world.gen.ChunkSource.getNearestStructurePos(ChunkSource.java:406)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.world.gen.ModernBetaChunkGenerator.func_180513_a(ModernBetaChunkGenerator.java:70)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:207)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at java.lang.Thread.run(Thread.java:745)
[16:52:09] [Server thread/ERROR]: Error in another mod's worldgen.  This is *NOT* a Galacticraft bug, report it to the other mod please.
[16:52:09] [Server thread/ERROR]: Details:- Dimension:58  Chunk cx,cz:-19,33  Seed:-6984854390176336655
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: java.lang.NullPointerException
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.api.world.gen.ChunkSource.getNearestStructurePos(ChunkSource.java:406)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at mod.bespectacled.modernbetaforge.world.gen.ModernBetaChunkGenerator.func_180513_a(ModernBetaChunkGenerator.java:70)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:207)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[16:52:09] [Server thread/INFO]: [micdoodle8.mods.galacticraft.core.TransformerHooks:otherModGenerate:212]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by b3spectacled** [comment] 2024-10-01 03:52
Closing since this is an old report and I cannot reproduce as of the latest version of Modern Beta. Thank you.

**Closed as completed by b3spectacled** 2024-10-01 03:52 UTC
